module.exports.MerchaindiseController = require("./merchaindise.controller")
module.exports.CategoryController = require("./category.controller")
module.exports.AuthController = require("./auth.controller")
module.exports.ViewController = require("./view.controller")
module.exports.UserController = require("./user.controller")
module.exports.PaymentController = require("./payment.controller")
module.exports.UserContractController = require("./userContract.controller")